In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

## CDC Patient Data

In [2]:
df = pd.read_csv('/Users/heloisabal/Final-project-DATA/XPT.csv',index_col=0)

In [3]:
df.shape

(445132, 326)

In [4]:
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,COLGSEX1,NUMADULT,LANDSEX1,NUMMEN,NUMWOMEN,RESPSLCT,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX1,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINSR,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,SLEPTIM1,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,RENTHOM1,NUMHHOL4,NUMPHON4,CPDEMO1C,VETERAN3,EMPLOY1,CHILDREN,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES2,SMALSTOL,STOLTEST,STOOLDN2,BLDSTFIT,SDNATES1,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW2,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSC1,LCSSCNCR,LCSCTWHN,ALCDAY4,AVEDRNK3,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,PNEUVAC4,TETANUS1,HIVTST7,HIVTSTD3,HIVRISK5,COVIDPOS,COVIDSMP,COVIDPRM,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,CHKHEMO3,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,TOLDCFS,HAVECFS,WORKCFS,IMFVPLA3,HPVADVC4,HPVADSHT,SHINGLE2,COVIDVA1,COVIDNU1,COVIDFS1,COVIDSE1,COPDCOGH,COPDFLEM,COPDBRTH,COPDBTST,COPDSMOK,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,PSATEST1,PSATIME1,PCPSARS2,PSASUGST,PCSTALK1,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,CAREGIV1,CRGVREL4,CRGVLNG1,CRGVHRS1,CRGVPRB3,CRGVALZD,CRGVPER1,CRGVHOU1,CRGVEXPT,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,LSATISFY,EMTSUPRT,SDHISOLT,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,SDHSTRE1,MARIJAN1,MARJSMOK,MARJEAT,MARJVAPE,MARJDAB,MARJOTHR,USEMRJN4,LASTSMK2,STOPSMK2,MENTCIGS,MENTECIG,HEATTBCO,ASBIALCH,ASBIDRNK,ASBIBING,ASBIADVC,ASBIRDUC,FIREARM5,GUNLOAD,LOADULK2,RCSGEND1,RCSXBRTH,RCSRLTN2,CASTHDX2,CASTHNO2,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,HADSEX,PFPPRVN4,TYPCNTR9,BRTHCNT4,WHEREGET,NOBCUSE8,BCPREFER,RRCLASS3,RRCOGNT2,RRTREAT,RRATWRK2,RRHCARE4,RRPHYSM2,QSTVER,QSTLANG,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE2,_CPRACE2,CAGEG,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_ALTETH3,_DENVST3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_RFMAM22,_MAM5023,_HADCOLN,_CLNSCP1,_HADSIGM,_SGMSCP1,_SGMS101,_RFBLDS5,_STOLDN1,_VIRCOL1,_SBONTI1,_CRCREC2,_SMOKER3,_RFSMOK3,_CURECI2,_YRSSMOK,_PACKDAY,_PACKYRS,_YRSQUIT,_SMOKGRP,_LCSREC,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,1.0,2032022,2,3,2022,1100.0,2022000001,2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,99.0,1.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,80.0,1.0,6.0,1.0,1.0,1.0,2.0,2.0,7.0,88.0,99.0,NaN,9999.0,9999.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,2.0,1.0,3.0,2.0,3.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,4.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,1.0,92021.0,2.0,3.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,2.0,11011.0,37.418416,2.0,74.836832,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0,4.0,9.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,1.0,2042022,2,4,2022,1100.0,2022000002,2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,88.0,88.0,NaN,3.0,2.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,3.0,NaN,3.0,4.0,1.0,1.0,2.0,1.0,2.0,2.0,88.0,5.0,NaN,150.0,503.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,4.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,4.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,2.0,NaN,2.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,2.0,1.0,5.0,11011.0,37.418416,1.0,37.418416,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,63.0,160.0,6804.0,2657.0,3.0,2.0,1.0,2.0,3.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0
2,1.0,1.0,2022022,2,2,2022,1100.0,2022000003,2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,1.0,6.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,10.0,NaN,140.0,502.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,2.0,NaN,2.0,7.0,2.0,NaN,2.0,1.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,2.0,11011.0,37.418416,1.0,37.418416,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,NaN,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,62.0,157.0,6350.0,2561.0,3.0,2.0,1.0,4.0,6.0,1.0,1.0,2.0,3.0,2.0,3.0,3.0,NaN,NaN,NaN,2.0,2.0,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0
3,1.0,1.0,2032022,2,3,2022,1100.0,2022000004,2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,3.0,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,88.0,88.0,NaN,99.0,1.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,1.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,77.0,2.0,140.0,505.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,7.0,2.0,1.0,1.0,3.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,3.0,1.0,17.0,999.0,2.0,1.0,2.0,NaN,888.0,NaN,NaN,NaN,1.0,102021.0,1.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,9.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,65.0,165.0,6350.0,2330.0,2.0,1.0,1.0,2.0,9.0,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,56.0,0.1,6.0,NaN,3.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,9.0,9.0,2.0
4,1.0,1.0,2022022,2,2,2022,1100.0,2022000005,2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,2.0,88.0,88.0,7.0,2.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,1.0,5.0,1.0,2.0,NaN,2.0,2.0,5.0,88.0,5.0,2.0,119.0,502.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,1.0,2.0,NaN,203.0,2.0,88.0,2.0,2.0,NaN,1.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,NaN,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,62.0,157.0,5398.0,2177.0,2.0,1.0,1.0,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,1.0,1.000000e+01,1.0,1.400000e+02,1.0,NaN,NaN,2.0

In [5]:
df['IYEAR'].unique()

array([2022, 2023])

In [6]:
df['IYEAR'].value_counts()

2022    419473
2023     25659
Name: IYEAR, dtype: int64

#### I only want data for 2022, therefore I will delete all rows for 2023

In [7]:
year_to_delete = 2023

In [8]:
df = df[df['IYEAR'] != year_to_delete]

In [9]:
df = df.reset_index(drop=True)

In [10]:
df.shape

(419473, 326)

In [11]:
# df.to_csv('final_data.csv', index=False)

In [12]:
df['IYEAR'].unique()

array([2022])

#### Checking the column descriptions

To DROP based on description:
- NUMHHOL4
- IDATE
- SEQNO
-  _PSU
- CTELENM1
- PVTRESD1
- COLGHOUS
- STATERE1
- CELPHON1
- LADULT1
- NUMADULT
- RESPSLCT
- CELLSEX1
- LANDSEX1
- NUMMEN
- NUMWOMEN
- SAFETIME
- CELLFON5
- CADULT1
- CSTATE1
- LANDLINE
- HHADULT
- PRIMINSR
- PERSDOC3


This one is gender: SEXVAR

In [13]:
df = df.drop(['NUMHHOL4','IDATE','SEQNO','_PSU','CTELENM1','PVTRESD1','COLGHOUS','STATERE1','CELPHON1','LADULT1',
              'NUMADULT','RESPSLCT','CELLSEX1','LANDSEX1','NUMMEN','NUMWOMEN','SAFETIME','CELLFON5','CADULT1',
              'CSTATE1','LANDLINE','HHADULT','PRIMINSR','PERSDOC3'], axis=1)

#### Checking for nulls in the columns

In [14]:
df.isna().sum()/len(df)

_STATE      0.000000
FMONTH      0.000000
IMONTH      0.000000
IDAY        0.000000
IYEAR       0.000000
              ...
_DRNKWK2    0.000000
_RFDRHV8    0.000000
_FLSHOT7    0.620772
_PNEUMO3    0.620772
_AIDTST4    0.101628
Length: 302, dtype: float64

In [15]:
nulls_percent_df = pd.DataFrame(df.isna().sum()*100/len(df)).reset_index()
nulls_percent_df
nulls_percent_df.columns = ['column_name', 'nulls_percentage']
nulls_percent_df

    column_name  nulls_percentage
0        _STATE          0.000000
1        FMONTH          0.000000
2        IMONTH          0.000000
3          IDAY          0.000000
4         IYEAR          0.000000
..          ...               ...
297    _DRNKWK2          0.000000
298    _RFDRHV8          0.000000
299    _FLSHOT7         62.077178
300    _PNEUMO3         62.077178
301    _AIDTST4         10.162752

[302 rows x 2 columns]

In [16]:
nulls_percent_df[nulls_percent_df['nulls_percentage']!=0]

    column_name  nulls_percentage
6      COLGSEX1         99.994994
7      CTELNUM1         21.793775
8      PVTRESD3         21.795443
9      CCLGHOUS         99.703676
11      GENHLTH          0.000715
..          ...               ...
293     _LCSREC         88.395916
295    DROCDY4_          0.000954
299    _FLSHOT7         62.077178
300    _PNEUMO3         62.077178
301    _AIDTST4         10.162752

[258 rows x 2 columns]

In [17]:
nulls_percent_df[nulls_percent_df['nulls_percentage']!=0].head(60)

   column_name  nulls_percentage
6     COLGSEX1         99.994994
7     CTELNUM1         21.793775
8     PVTRESD3         21.795443
9     CCLGHOUS         99.703676
11     GENHLTH          0.000715
12    PHYSHLTH          0.001192
13    MENTHLTH          0.000715
14    POORHLTH         42.659718
15    MEDCOST1          0.000954
16    CHECKUP1          0.000715
17    EXERANY2          0.000477
18    SLEPTIM1          0.000715
19    LASTDEN4          0.324932
20    RMVTETH4          0.324932
21    CVDINFR4          0.000954
22    CVDCRHD4          0.000477
23    CVDSTRK3          0.000477
24     ASTHMA3          0.000477
25     ASTHNOW         85.014530
26    CHCSCNC1          0.000477
27    CHCOCNC1          0.000715
28    CHCCOPD3          0.000477
29    ADDEPEV3          0.001669
30    CHCKDNY2          0.000477
31    HAVARTH4          0.000715
32    DIABETE4          0.000715
33    DIABAGE4         86.230818
34     MARITAL          0.001669
35       EDUCA          0.000954
36    RENTHOM1          0.001907
37    NUMPHON4         98.427312
38    CPDEMO1C          0.625785
39    VETERAN3          0.923063
40     EMPLOY1          1.366000
41    CHILDREN          2.051622
42     INCOME3          2.847144
43    PREGNANT         82.288491
44     WEIGHT2          3.498676
45     HEIGHT3          3.751135
46        DEAF          4.100621
47       BLIND          4.363570
48      DECIDE          4.611262
49    DIFFWALK          4.872066
50    DIFFDRES          5.032267
51    DIFFALON          5.266132
52      HADMAM         50.085703
53     HOWLONG         61.466173
54    CERVSCRN         50.306694
55    CRVCLCNC         69.518658
56    CRVCLPAP         69.559662
57    CRVCLHPV         69.607579
58    HADHYST2         51.006382
59    HADSIGM4         34.088010
60    COLNSIGM         52.035530
61    COLNTES1         53.278280
62    SIGMTES1         92.946387
63    LASTSIG4         99.217590
64    COLNCNCR         34.443456
65    VIRCOLO1         86.114720
66    VCLNTES2         97.978177

In [18]:
df.shape

(419473, 302)

In [19]:
columns_above_th = nulls_percent_df[nulls_percent_df['nulls_percentage']>0.80]
columns_above_th['column_name']

6      COLGSEX1
7      CTELNUM1
8      PVTRESD3
9      CCLGHOUS
14     POORHLTH
         ...
292    _SMOKGRP
293     _LCSREC
299    _FLSHOT7
300    _PNEUMO3
301    _AIDTST4
Name: column_name, Length: 225, dtype: object

In [20]:
drop_columns_list = list(columns_above_th['column_name'])
drop_columns_list

['COLGSEX1',
 'CTELNUM1',
 'PVTRESD3',
 'CCLGHOUS',
 'POORHLTH',
 'ASTHNOW',
 'DIABAGE4',
 'NUMPHON4',
 'VETERAN3',
 'EMPLOY1',
 'CHILDREN',
 'INCOME3',
 'PREGNANT',
 'WEIGHT2',
 'HEIGHT3',
 'DEAF',
 'BLIND',
 'DECIDE',
 'DIFFWALK',
 'DIFFDRES',
 'DIFFALON',
 'HADMAM',
 'HOWLONG',
 'CERVSCRN',
 'CRVCLCNC',
 'CRVCLPAP',
 'CRVCLHPV',
 'HADHYST2',
 'HADSIGM4',
 'COLNSIGM',
 'COLNTES1',
 'SIGMTES1',
 'LASTSIG4',
 'COLNCNCR',
 'VIRCOLO1',
 'VCLNTES2',
 'SMALSTOL',
 'STOLTEST',
 'STOOLDN2',
 'BLDSTFIT',
 'SDNATES1',
 'SMOKE100',
 'SMOKDAY2',
 'USENOW3',
 'ECIGNOW2',
 'LCSFIRST',
 'LCSLAST',
 'LCSNUMCG',
 'LCSCTSC1',
 'LCSSCNCR',
 'LCSCTWHN',
 'ALCDAY4',
 'AVEDRNK3',
 'DRNK3GE5',
 'MAXDRNKS',
 'FLUSHOT7',
 'FLSHTMY3',
 'PNEUVAC4',
 'TETANUS1',
 'HIVTST7',
 'HIVTSTD3',
 'HIVRISK5',
 'COVIDPOS',
 'COVIDSMP',
 'COVIDPRM',
 'PDIABTS1',
 'PREDIAB2',
 'DIABTYPE',
 'INSULIN1',
 'CHKHEMO3',
 'EYEEXAM1',
 'DIABEYE1',
 'DIABEDU1',
 'FEETSORE',
 'TOLDCFS',
 'HAVECFS',
 'WORKCFS',
 'IMFVPLA3',
 'HPVADVC4',
 'HPVADSHT',
 'SHINGLE2',
 'COVIDVA1',
 'COVIDNU1',
 'COVIDFS1',
 'COVIDSE1',
 'COPDCOGH',
 'COPDFLEM',
 'COPDBRTH',
 'COPDBTST',
 'COPDSMOK',
 'CNCRDIFF',
 'CNCRAGE',
 'CNCRTYP2',
 'CSRVTRT3',
 'CSRVDOC1',
 'CSRVSUM',
 'CSRVRTRN',
 'CSRVINST',
 'CSRVINSR',
 'CSRVDEIN',
 'CSRVCLIN',
 'CSRVPAIN',
 'CSRVCTL2',
 'PSATEST1',
 'PSATIME1',
 'PCPSARS2',
 'PSASUGST',
 'PCSTALK1',
 'CIMEMLOS',
 'CDHOUSE',
 'CDASSIST',
 'CDHELP',
 'CDSOCIAL',
 'CDDISCUS',
 'CAREGIV1',
 'CRGVREL4',
 'CRGVLNG1',
 'CRGVHRS1',
 'CRGVPRB3',
 'CRGVALZD',
 'CRGVPER1',
 'CRGVHOU1',
 'CRGVEXPT',
 'ACEDEPRS',
 'ACEDRINK',
 'ACEDRUGS',
 'ACEPRISN',
 'ACEDIVRC',
 'ACEPUNCH',
 'ACEHURT1',
 'ACESWEAR',
 'ACETOUCH',
 'ACETTHEM',
 'ACEHVSEX',
 'ACEADSAF',
 'ACEADNED',
 'LSATISFY',
 'EMTSUPRT',
 'SDHISOLT',
 'SDHEMPLY',
 'FOODSTMP',
 'SDHFOOD1',
 'SDHBILLS',
 'SDHUTILS',
 'SDHTRNSP',
 'SDHSTRE1',
 'MARIJAN1',
 'MARJSMOK',
 'MARJEAT',
 'MARJVAPE',
 'MARJDAB',
 'MARJOTHR',
 'USEMRJN4',
 'LASTSMK2',
 'STOPSMK2',
 'MENTCIGS',
 'MENTECIG',
 'HEATTBCO',
 'ASBIALCH',
 'ASBIDRNK',
 'ASBIBING',
 'ASBIADVC',
 'ASBIRDUC',
 'FIREARM5',
 'GUNLOAD',
 'LOADULK2',
 'RCSGEND1',
 'RCSXBRTH',
 'RCSRLTN2',
 'CASTHDX2',
 'CASTHNO2',
 'BIRTHSEX',
 'SOMALE',
 'SOFEMALE',
 'TRNSGNDR',
 'HADSEX',
 'PFPPRVN4',
 'TYPCNTR9',
 'BRTHCNT4',
 'WHEREGET',
 'NOBCUSE8',
 'BCPREFER',
 'RRCLASS3',
 'RRCOGNT2',
 'RRTREAT',
 'RRATWRK2',
 'RRHCARE4',
 'RRPHYSM2',
 '_METSTAT',
 '_URBSTAT',
 'MSCODE',
 '_CHISPNC',
 '_CRACE2',
 '_CPRACE2',
 'CAGEG',
 '_CLLCPWT',
 '_DUALCOR',
 '_ALTETH3',
 '_MICHD',
 'HTIN4',
 'HTM4',
 'WTKG3',
 '_BMI5',
 '_BMI5CAT',
 '_RFMAM22',
 '_MAM5023',
 '_HADCOLN',
 '_CLNSCP1',
 '_HADSIGM',
 '_SGMSCP1',
 '_SGMS101',
 '_RFBLDS5',
 '_STOLDN1',
 '_VIRCOL1',
 '_SBONTI1',
 '_CRCREC2',
 '_YRSSMOK',
 '_PACKDAY',
 '_PACKYRS',
 '_YRSQUIT',
 '_SMOKGRP',
 '_LCSREC',
 '_FLSHOT7',
 '_PNEUMO3',
 '_AIDTST4']

In [21]:
len(drop_columns_list)

225

In [22]:
df = df.drop(columns=drop_columns_list)

In [23]:
df

,_STATE,FMONTH,IMONTH,IDAY,IYEAR,DISPCODE,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,MEDCOST1,CHECKUP1,EXERANY2,SLEPTIM1,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,MARITAL,EDUCA,RENTHOM1,CPDEMO1C,QSTVER,QSTLANG,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_DUALUSE,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_DENVST3,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8
0,1.0,1.0,2,3,2022,1100.0,2.0,2.0,88.0,88.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,6.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,9.0,1.0,4.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
1,1.0,1.0,2,4,2022,1100.0,2.0,1.0,88.0,88.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,2.0,1.0,2.0,3.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
2,1.0,1.0,2,2,2022,1100.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,6.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,2.0,1.0,4.0,6.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
3,1.0,1.0,2,3,2022,1100.0,2.0,1.0,88.0,88.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,1.0,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,1.0,1.0,2.0,9.0,2.0,2.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
4,1.0,1.0,2,2,2022,1100.0,2.0,4.0,2.0,88.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,5.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,1.0,1.0,3.0,3.0,4.0,1.0,1.0,1.0,1.000000e+01,1.0,1.400000e+02,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419468,78.0,11.0,12,19,2022,1100.0,2.0,3.0,88.0,3.0,2.0,2.0,1.0,6.0,2.0,8.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,3.0,5.0,4.0,2.0,2.0,20.0,1.0,782021.0,6.757070,1.0,6.757070,2.0,9.0,26.121098,37.309732,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,19.0,1.0,2.0,2.0,2.0,1.0,4.0,1.0,1.0,7.0,9.000000e+02,9.0,9.990000e+04,9.0
419469,78.0,11.0,12,21,2022,1100.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,7.0,1.0,8.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,6.0,1.0,1.0,20.0,1.0,782021.0,6.757070,1.0,6.757070,2.0,2.0,106.070791,103.712331,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,7.0,1.0,51.0,4.0,2.0,2.0,4.0,5.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
419470,78.0,11.0,11,29,2022,1100.0,2.0,5.0,30.0,30.0,1.0,4.0,2.0,5.0,4.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,4.0,3.0,1.0,20.0,1.0,782021.0,6.757070,1.0,6.757070,2.0,9.0,26.121098,4.781602,2.0,3.0,3.0,2.0,9.0,2.0,2.0,2.0,1.0,1.0,3.0,2.0,99.0,99.0,2.0,9.0,9.0,9.0,2.0,2.0,10.0,2.0,65.0,6.0,1.0,1.0,2.0,9.0,1.0,2.0,2.0,7.0,9.000000e+02,9.0,9.990000e+04,9.0
419471,78.0,11.0,12,8,2022,1100.0,1.0,2.0,88.0,88.0,2.0,1.0,2.0,5.0,1.0,8.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,5.0,2.0,1.0,20.0,1.0,782021.0,6.757070,1.0,6.757070,2.0,9.0,29.302884,8.269244,1.0,1.0,1.0,1.0,9.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,11.0,2.0,73.0,6.0,2.0,1.0,3.0,5.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
419472,78.0,11.0,12,14,2022,1100.0,1.0,2.0,88.0,1.0,1.0,8.0,1.0,5.0,8.0,8.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,1.0,1.0,20.0,1.0,782021.0,6.757070,1.0,6.757070,2.0,9.0,26.121098,368.817758,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,5.0,1.0,42.0,3.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,5.000000e+01,2.0,9.990000e+04,9.0

In [24]:
df.columns

Index(['_STATE', 'FMONTH', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE', 'SEXVAR',
       'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'MEDCOST1', 'CHECKUP1', 'EXERANY2',
       'SLEPTIM1', 'LASTDEN4', 'RMVTETH4', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3',
       'ASTHMA3', 'CHCSCNC1', 'CHCOCNC1', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2',
       'HAVARTH4', 'DIABETE4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'CPDEMO1C',
       'QSTVER', 'QSTLANG', '_STSTR', '_STRWT', '_RAWRAKE', '_WT2RAKE',
       '_IMPRACE', '_DUALUSE', '_LLCPWT2', '_LLCPWT', '_RFHLTH', '_PHYS14D',
       '_MENT14D', '_HLTHPLN', '_HCVU652', '_TOTINDA', '_EXTETH3', '_DENVST3',
       '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR2', '_PRACE2', '_MRACE2',
       '_HISPANC', '_RACE1', '_RACEG22', '_RACEGR4', '_RACEPR1', '_SEX',
       '_AGEG5YR', '_AGE65YR', '_AGE80', '_AGE_G', '_RFBMI5', '_CHLDCNT',
       '_EDUCAG', '_INCOMG1', '_SMOKER3', '_RFSMOK3', '_CURECI2', 'DRNKANY6',
       'DROCDY4_', '_RFBING6', '_DRNKWK2', '_RFDRHV8'],
      dtype='object')

In [25]:
state_mapping = {
    1: 'Alabama',
    2: 'Alaska',
    4: 'Arizona',
    5: 'Arkansas',
    6: 'California',
    8: 'Colorado',
    9: 'Connecticut',
    10: 'Delaware',
    11: 'District of Columbia',
    12: 'Florida',
    13: 'Georgia',
    15: 'Hawaii',
    16: 'Idaho',
    17: 'Illinois',
    18: 'Indiana',
    19: 'Iowa',
    20: 'Kansas',
    21: 'Kentucky',
    22: 'Louisiana',
    23: 'Maine',
    24: 'Maryland',
    25: 'Massachusetts',
    26: 'Michigan',
    27: 'Minnesota',
    28: 'Mississippi',
    29: 'Missouri',
    30: 'Montana',
    31: 'Nebraska',
    32: 'Nevada',
    33: 'New Hampshire',
    34: 'New Jersey',
    35: 'New Mexico',
    36: 'New York',
    37: 'North Carolina',
    38: 'North Dakota',
    39: 'Ohio',
    40: 'Oklahoma',
    41: 'Oregon',
    42: 'Pennsylvania',
    44: 'Rhode Island',
    45: 'South Carolina',
    46: 'South Dakota',
    47: 'Tennessee',
    48: 'Texas',
    49: 'Utah',
    50: 'Vermont',
    51: 'Virginia',
    53: 'Washington',
    54: 'West Virginia',
    55: 'Wisconsin',
    56: 'Wyoming',
    66: 'Guam',
    72: 'Puerto Rico',
    78: 'Virgin Islands'
}

In [26]:
df['_STATE'] = df['_STATE'].replace(state_mapping)

In [27]:
df.head()

,_STATE,FMONTH,IMONTH,IDAY,IYEAR,DISPCODE,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,MEDCOST1,CHECKUP1,EXERANY2,SLEPTIM1,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,MARITAL,EDUCA,RENTHOM1,CPDEMO1C,QSTVER,QSTLANG,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_DUALUSE,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_DENVST3,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8
0,Alabama,1.0,2,3,2022,1100.0,2.0,2.0,88.0,88.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,6.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,9.0,1.0,4.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
1,Alabama,1.0,2,4,2022,1100.0,2.0,1.0,88.0,88.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,2.0,1.0,2.0,3.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
2,Alabama,1.0,2,2,2022,1100.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,6.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,2.0,1.0,4.0,6.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
3,Alabama,1.0,2,3,2022,1100.0,2.0,1.0,88.0,88.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,1.0,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,1.0,1.0,2.0,9.0,2.0,2.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
4,Alabama,1.0,2,2,2022,1100.0,2.0,4.0,2.0,88.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,5.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,1.0,1.0,3.0,3.0,4.0,1.0,1.0,1.0,1.000000e+01,1.0,1.400000e+02,1.0

In [28]:
df['_STATE'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming', 'Guam', 'Puerto Rico',
       'Virgin Islands'], dtype=object)

In [29]:
df.iloc[419469]

_STATE      Virgin Islands
FMONTH                11.0
IMONTH                  12
IDAY                    21
IYEAR                 2022
                 ...
DRNKANY6               2.0
DROCDY4_               0.0
_RFBING6               1.0
_DRNKWK2               0.0
_RFDRHV8               1.0
Name: 419469, Length: 77, dtype: object

In [30]:
df.head()

,_STATE,FMONTH,IMONTH,IDAY,IYEAR,DISPCODE,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,MEDCOST1,CHECKUP1,EXERANY2,SLEPTIM1,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,MARITAL,EDUCA,RENTHOM1,CPDEMO1C,QSTVER,QSTLANG,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_DUALUSE,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_DENVST3,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8
0,Alabama,1.0,2,3,2022,1100.0,2.0,2.0,88.0,88.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,6.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,9.0,1.0,4.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
1,Alabama,1.0,2,4,2022,1100.0,2.0,1.0,88.0,88.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,2.0,1.0,2.0,3.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
2,Alabama,1.0,2,2,2022,1100.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,6.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,2.0,1.0,4.0,6.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
3,Alabama,1.0,2,3,2022,1100.0,2.0,1.0,88.0,88.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,1.0,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,1.0,1.0,2.0,9.0,2.0,2.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0
4,Alabama,1.0,2,2,2022,1100.0,2.0,4.0,2.0,88.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,5.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,1.0,1.0,3.0,3.0,4.0,1.0,1.0,1.0,1.000000e+01,1.0,1.400000e+02,1.0

### Removing additional columns that are not useful

In [31]:
df = df.drop(['FMONTH','IMONTH','IDAY','IYEAR','DISPCODE','_RFBING6'], axis=1)

In [32]:
df.head()

,_STATE,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,MEDCOST1,CHECKUP1,EXERANY2,SLEPTIM1,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,MARITAL,EDUCA,RENTHOM1,CPDEMO1C,QSTVER,QSTLANG,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_DUALUSE,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_DENVST3,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_DRNKWK2,_RFDRHV8
0,Alabama,2.0,2.0,88.0,88.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,6.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,9.0,1.0,4.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
1,Alabama,2.0,1.0,88.0,88.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,2.0,1.0,2.0,3.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
2,Alabama,2.0,2.0,2.0,3.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,6.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,2.0,1.0,4.0,6.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
3,Alabama,2.0,1.0,88.0,88.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,1.0,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,1.0,1.0,2.0,9.0,2.0,2.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
4,Alabama,2.0,4.0,2.0,88.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,5.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,1.0,1.0,3.0,3.0,4.0,1.0,1.0,1.0,1.000000e+01,1.400000e+02,1.0

In [33]:
df['SEXVAR'].value_counts()

2.0    222388
1.0    197085
Name: SEXVAR, dtype: int64

In [34]:
gender = {1: 'Male', 2: 'Female'}

In [35]:
df['SEXVAR'] = df['SEXVAR'].replace(gender)

In [36]:
df.head()

,_STATE,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,MEDCOST1,CHECKUP1,EXERANY2,SLEPTIM1,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,MARITAL,EDUCA,RENTHOM1,CPDEMO1C,QSTVER,QSTLANG,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_DUALUSE,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_DENVST3,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_DRNKWK2,_RFDRHV8
0,Alabama,Female,2.0,88.0,88.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,6.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,9.0,1.0,4.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
1,Alabama,Female,1.0,88.0,88.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,2.0,1.0,2.0,3.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
2,Alabama,Female,2.0,2.0,3.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,6.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,2.0,1.0,4.0,6.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
3,Alabama,Female,1.0,88.0,88.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,1.0,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,1.0,1.0,2.0,9.0,2.0,2.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
4,Alabama,Female,4.0,2.0,88.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,5.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,1.0,1.0,3.0,3.0,4.0,1.0,1.0,1.0,1.000000e+01,1.400000e+02,1.0

In [37]:
column_mapping = {
    '_STATE': 'STATE',
    'SEXVAR': 'GENDER',
    'SLEPTIM1': 'SLEEP_TIME',
}

In [38]:
df.rename(columns=column_mapping, inplace=True)

In [39]:
df.head()

,STATE,GENDER,GENHLTH,PHYSHLTH,MENTHLTH,MEDCOST1,CHECKUP1,EXERANY2,SLEEP_TIME,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,MARITAL,EDUCA,RENTHOM1,CPDEMO1C,QSTVER,QSTLANG,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_DUALUSE,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_DENVST3,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_DRNKWK2,_RFDRHV8
0,Alabama,Female,2.0,88.0,88.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,6.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,9.0,1.0,4.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
1,Alabama,Female,1.0,88.0,88.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,2.0,1.0,2.0,3.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
2,Alabama,Female,2.0,2.0,3.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,6.0,1.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,2.0,1.0,4.0,6.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
3,Alabama,Female,1.0,88.0,88.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,10.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,1.0,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,1.0,1.0,2.0,9.0,2.0,2.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
4,Alabama,Female,4.0,2.0,88.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,5.0,1.0,2.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,1.0,1.0,3.0,3.0,4.0,1.0,1.0,1.0,1.000000e+01,1.400000e+02,1.0

In [40]:
df.shape

(419473, 71)

In [41]:
nulls_percent = pd.DataFrame(df.isna().sum()*100/len(df)).reset_index()
nulls_percent
nulls_percent.columns = ['column_name', 'nulls_percentage']
nulls_percent

   column_name  nulls_percentage
0        STATE          0.000000
1       GENDER          0.000000
2      GENHLTH          0.000715
3     PHYSHLTH          0.001192
4     MENTHLTH          0.000715
..         ...               ...
66    _CURECI2          0.000000
67    DRNKANY6          0.000000
68    DROCDY4_          0.000954
69    _DRNKWK2          0.000000
70    _RFDRHV8          0.000000

[71 rows x 2 columns]

In [42]:
columns_above_threshold = nulls_percent[nulls_percent['nulls_percentage']>0.20]
columns_above_threshold['column_name']

9     LASTDEN4
10    RMVTETH4
25    CPDEMO1C
47    _DRDXAR2
Name: column_name, dtype: object

In [43]:
drop_list = list(columns_above_threshold['column_name'])
drop_list

['LASTDEN4', 'RMVTETH4', 'CPDEMO1C', '_DRDXAR2']

In [44]:
df = df.drop(drop_list, axis=1)

In [45]:
df.shape

(419473, 67)

In [46]:
df.head()

,STATE,GENDER,GENHLTH,PHYSHLTH,MENTHLTH,MEDCOST1,CHECKUP1,EXERANY2,SLEEP_TIME,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,MARITAL,EDUCA,RENTHOM1,QSTVER,QSTLANG,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_DUALUSE,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_DENVST3,_LTASTH1,_CASTHM1,_ASTHMS1,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_DRNKWK2,_RFDRHV8
0,Alabama,Female,2.0,88.0,88.0,2.0,1.0,2.0,8.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,6.0,1.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,9.0,1.0,4.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
1,Alabama,Female,1.0,88.0,88.0,2.0,8.0,2.0,6.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,2.0,1.0,2.0,3.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
2,Alabama,Female,2.0,2.0,3.0,2.0,1.0,1.0,5.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,6.0,1.0,10.0,1.0,11011.0,37.418416,1.0,37.418416,1.0,1.0,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,2.0,1.0,4.0,6.0,4.0,1.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
3,Alabama,Female,1.0,88.0,88.0,2.0,1.0,1.0,7.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,10.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,1.0,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,1.0,1.0,2.0,9.0,2.0,2.0,1.0,2.0,5.397605e-79,5.397605e-79,1.0
4,Alabama,Female,4.0,2.0,88.0,2.0,1.0,1.0,9.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,5.0,1.0,10.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,1.0,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,9.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,1.0,1.0,3.0,3.0,4.0,1.0,1.0,1.0,1.000000e+01,1.400000e+02,1.0

In [47]:
nulls = pd.DataFrame(df.isna().sum()*100/len(df)).reset_index()
nulls
nulls.columns = ['column_name', 'nulls_percentage']
nulls[nulls['nulls_percentage']!=0]

   column_name  nulls_percentage
2      GENHLTH          0.000715
3     PHYSHLTH          0.001192
4     MENTHLTH          0.000715
5     MEDCOST1          0.000954
6     CHECKUP1          0.000715
7     EXERANY2          0.000477
8   SLEEP_TIME          0.000715
9     CVDINFR4          0.000954
10    CVDCRHD4          0.000477
11    CVDSTRK3          0.000477
12     ASTHMA3          0.000477
13    CHCSCNC1          0.000477
14    CHCOCNC1          0.000715
15    CHCCOPD3          0.000477
16    ADDEPEV3          0.001669
17    CHCKDNY2          0.000477
18    HAVARTH4          0.000715
19    DIABETE4          0.000715
20     MARITAL          0.001669
21       EDUCA          0.000954
22    RENTHOM1          0.001907
40    _DENVST3          0.000954
44     _PRACE2          0.002622
45     _MRACE2          0.002146
47      _RACE1          0.000477
48    _RACEG22          0.000477
49    _RACEGR4          0.000477
57    _CHLDCNT          0.000238
64    DROCDY4_          0.000954

In [48]:
nulls[nulls['nulls_percentage']!=0].head(60)

   column_name  nulls_percentage
2      GENHLTH          0.000715
3     PHYSHLTH          0.001192
4     MENTHLTH          0.000715
5     MEDCOST1          0.000954
6     CHECKUP1          0.000715
7     EXERANY2          0.000477
8   SLEEP_TIME          0.000715
9     CVDINFR4          0.000954
10    CVDCRHD4          0.000477
11    CVDSTRK3          0.000477
12     ASTHMA3          0.000477
13    CHCSCNC1          0.000477
14    CHCOCNC1          0.000715
15    CHCCOPD3          0.000477
16    ADDEPEV3          0.001669
17    CHCKDNY2          0.000477
18    HAVARTH4          0.000715
19    DIABETE4          0.000715
20     MARITAL          0.001669
21       EDUCA          0.000954
22    RENTHOM1          0.001907
40    _DENVST3          0.000954
44     _PRACE2          0.002622
45     _MRACE2          0.002146
47      _RACE1          0.000477
48    _RACEG22          0.000477
49    _RACEGR4          0.000477
57    _CHLDCNT          0.000238
64    DROCDY4_          0.000954

In [49]:
df.shape

(419473, 67)

I will drop _SEX, as it represents the same as GENDER

In [50]:
to_see = df[['GENDER','_SEX']]
to_see.head(20)

    GENDER  _SEX
0   Female   2.0
1   Female   2.0
2   Female   2.0
3   Female   2.0
4   Female   2.0
5     Male   1.0
6   Female   2.0
7   Female   2.0
8   Female   2.0
9   Female   2.0
10  Female   2.0
11  Female   2.0
12    Male   1.0
13    Male   1.0
14  Female   2.0
15  Female   2.0
16  Female   2.0
17  Female   2.0
18  Female   2.0
19  Female   2.0

In [51]:
df = df.drop(['_SEX'], axis=1)

In [52]:
check = df[['ASTHMA3','_LTASTH1']]
check.head(20)

    ASTHMA3  _LTASTH1
0       2.0       1.0
1       2.0       1.0
2       2.0       1.0
3       1.0       2.0
4       2.0       1.0
5       2.0       1.0
6       2.0       1.0
7       2.0       1.0
8       2.0       1.0
9       2.0       1.0
10      2.0       1.0
11      2.0       1.0
12      1.0       2.0
13      2.0       1.0
14      2.0       1.0
15      2.0       1.0
16      2.0       1.0
17      1.0       2.0
18      2.0       1.0
19      2.0       1.0

I will drop _LTASTH1 and ASTHMA3, will keep _CASTHM1 (Adults who have been told they currently have asthma)

In [53]:
df = df.drop(['_LTASTH1','ASTHMA3'], axis=1)

In [54]:
df.columns

Index(['STATE', 'GENDER', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'MEDCOST1',
       'CHECKUP1', 'EXERANY2', 'SLEEP_TIME', 'CVDINFR4', 'CVDCRHD4',
       'CVDSTRK3', 'CHCSCNC1', 'CHCOCNC1', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2',
       'HAVARTH4', 'DIABETE4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'QSTVER',
       'QSTLANG', '_STSTR', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_IMPRACE',
       '_DUALUSE', '_LLCPWT2', '_LLCPWT', '_RFHLTH', '_PHYS14D', '_MENT14D',
       '_HLTHPLN', '_HCVU652', '_TOTINDA', '_EXTETH3', '_DENVST3', '_CASTHM1',
       '_ASTHMS1', '_PRACE2', '_MRACE2', '_HISPANC', '_RACE1', '_RACEG22',
       '_RACEGR4', '_RACEPR1', '_AGEG5YR', '_AGE65YR', '_AGE80', '_AGE_G',
       '_RFBMI5', '_CHLDCNT', '_EDUCAG', '_INCOMG1', '_SMOKER3', '_RFSMOK3',
       '_CURECI2', 'DRNKANY6', 'DROCDY4_', '_DRNKWK2', '_RFDRHV8'],
      dtype='object')

### Columns to remove based on description:

- MEDCOST1
- CHECKUP1
- EXERANY2
- EDUCA
- RENTHOM1
- QSTVER
- QSTLANG
- _STSTR
- _STRWT
- _RAWRAKE
- _WT2RAKE
- _IMPRACE
- _DUALUSE
- _LLCPWT2
- _LLCPWT
- _RFHLTH
- _MENT14D
- QSTVER
- _HLTHPLN
- _HCVU652
- _EXTETH3
- _DENVST3
- _ASTHMS1
- _MRACE2
- _HISPANC
- _PRACE2
- _RACEG22
- _RACEGR4
- _RACEPR1
- _AGE65YR
- _AGE80
- _AGEG5YR
- _CHLDCNT
- _EDUCAG
- DROCDY4_

In [55]:
columns_to_drop = [
    'MEDCOST1', 'CHECKUP1', 'EXERANY2', 'EDUCA', 'RENTHOM1', 'QSTVER',
    'QSTLANG', '_STSTR', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_IMPRACE',
    '_DUALUSE', '_LLCPWT2', '_LLCPWT', '_RFHLTH', '_MENT14D', 'QSTVER',
    '_HLTHPLN', '_HCVU652', '_EXTETH3', '_DENVST3', '_ASTHMS1', '_MRACE2',
    '_HISPANC', '_PRACE2', '_RACEG22', '_RACEGR4', '_RACEPR1', '_AGE65YR',
    '_AGE80', '_AGEG5YR', '_CHLDCNT', '_EDUCAG', 'DROCDY4_'
]

df.drop(columns=columns_to_drop, inplace=True)

### Columns to rename

- CVDINFR4: 'HEART_ATTACK'
- CVDCRHD4: 'ANGINA_HEART_DIS'
- CVDSTRK3: 'STROKE'
- ASTHMA3: 'ASTHMA'
- CHCSCNC1: 'SKIN_CANC_N_MELAN'
- CHCOCNC1: 'MELANOMA'
- CHCCOPD3: 'BRONCHITIS'
- ADDEPEV3: 'DEPRESSION'
- CHCKDNY2: KIDNEY_DISEASE_N_STO
- HAVARTH4: 'ARTHRITIS'
- DIABETE4: 'DIABETES'
- _PHYS14D: 'HEALTH_STATUS'
- _SMOKER3: 'SMOKING_STATUS'
- _RFSMOK3': 'CURRENT_SMOKER'
- _TOTINDA: 'PHYSICAL_ACTIVITY_30D'
- _CASTHM1: 'ASTHMA'
- _RACE1: 'RACE'
- _AGE_G: 'AGE'
- _RFBMI5: 'BMI_>25'
- _INCOMG1: 'INCOME'
- _CURECI2: 'E_CIG_USER'
- DRNKANY6: 'ONE_DRINK_PAST30DAYS'
- _DRNKWK2: 'ALC_DRINKS_PER_W'
- _RFDRHV8: 'HEAVY_DRINKER'

In [56]:
df.rename(columns={
    'CVDINFR4': 'HEART_ATTACK',
    'CVDCRHD4': 'ANGINA_HEART_DIS',
    'CVDSTRK3': 'STROKE',
    'ASTHMA3': 'ASTHMA',
    'CHCSCNC1': 'SKIN_CANC_N_MELAN',
    'CHCOCNC1': 'MELANOMA',
    'CHCCOPD3': 'BRONCHITIS',
    'ADDEPEV3': 'DEPRESSION',
    'CHCKDNY2': 'KIDNEY_DISEASE_N_STO',
    'HAVARTH4': 'ARTHRITIS',
    'DIABETE4': 'DIABETES',
    '_PHYS14D': 'HEALTH_STATUS',
    '_SMOKER3': 'SMOKING_STATUS',
    '_RFSMOK3': 'CURRENT_SMOKER',
    '_TOTINDA': 'PHYSICAL_ACTIVITY_30D',
    '_CASTHM1': 'ASTHMA',
    '_RACE1': 'RACE',
    '_AGE_G': 'AGE',
    '_RFBMI5': 'BMI_>25',
    '_INCOMG1': 'INCOME',
    '_CURECI2': 'E_CIG_USER',
    'DRNKANY6': 'ONE_DRINK_PAST30DAYS',
    '_DRNKWK2': 'ALC_DRINKS_PER_W',
    '_RFDRHV8': 'HEAVY_DRINKER'
}, inplace=True)

In [59]:
df.head()

,STATE,GENDER,GENHLTH,PHYSHLTH,MENTHLTH,SLEEP_TIME,HEART_ATTACK,ANGINA_HEART_DIS,STROKE,SKIN_CANC_N_MELAN,MELANOMA,BRONCHITIS,DEPRESSION,KIDNEY_DISEASE_N_STO,ARTHRITIS,DIABETES,MARITAL,HEALTH_STATUS,PHYSICAL_ACTIVITY_30D,ASTHMA,RACE,AGE,BMI_>25,INCOME,SMOKING_STATUS,CURRENT_SMOKER,E_CIG_USER,ONE_DRINK_PAST30DAYS,ALC_DRINKS_PER_W,HEAVY_DRINKER
0,Alabama,Female,2.0,88.0,88.0,8.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,6.0,9.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0
1,Alabama,Female,1.0,88.0,88.0,6.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,1.0,2.0,1.0,1.0,6.0,2.0,3.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0
2,Alabama,Female,2.0,2.0,3.0,5.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,1.0,1.0,1.0,5.0,2.0,6.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0
3,Alabama,Female,1.0,88.0,88.0,7.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,6.0,1.0,9.0,2.0,2.0,1.0,2.0,5.397605e-79,1.0
4,Alabama,Female,4.0,2.0,88.0,9.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,1.400000e+02,1.0

In [60]:
df.shape

(419473, 30)

## Imbalanced data, based on the stroke column
- Treat this later in the process

Ever Diagnosed with a Stroke?

- 1: Yes	
- 2: No	
- 7: Don’t know/Not sure	
- 9: Refused	
- BLANK: Not asked or Missing

In [58]:
df['STROKE'].value_counts()

2.0    399780
1.0     18214
7.0      1213
9.0       264
Name: STROKE, dtype: int64

## Notes about columns TO KEEP
- _DRNKWK2: Calculated total number of alcoholic beverages consumed per week
- _AIDTST4: Adults who have ever been tested for HIV
-  _YRSQUIT: Number of years since quit smoking cigarettes
- DROCDY: Drink-occasions-per-day

## Apple Health Data

https://docs.python.org/3/library/xml.etree.elementtree.html

#### Check here for possibility to read this, otherwise need to find a different dataset

In [68]:
file = pd.read_xml('/Users/heloisabal/Final-project-DATA/export.xml')
file

,value,HKCharacteristicTypeIdentifierDateOfBirth,HKCharacteristicTypeIdentifierBiologicalSex,HKCharacteristicTypeIdentifierBloodType,HKCharacteristicTypeIdentifierFitzpatrickSkinType,HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse,type,sourceName,sourceVersion,unit,creationDate,startDate,endDate,MetadataEntry,device,workoutActivityType,duration,durationUnit,WorkoutStatistics,WorkoutEvent,WorkoutRoute,dateComponents,activeEnergyBurned,activeEnergyBurnedGoal,activeEnergyBurnedUnit,appleMoveTime,appleMoveTimeGoal,appleExerciseTime,appleExerciseTimeGoal,appleStandHours,appleStandHoursGoal,HeartRateVariabilityMetadataList
0,2023-09-21 17:35:09 +0100,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,1997-03-01,HKBiologicalSexFemale,HKBloodTypeNotSet,HKFitzpatrickSkinTypeNotSet,None,None,None,None,None,None,None,None,NaN,None,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,167,None,None,None,None,None,HKQuantityTypeIdentifierHeight,Heloisa’s Iphone 🌸,15.2,cm,2022-01-10 16:17:02 +0100,2022-01-10 16:17:02 +0100,2022-01-10 16:17:02 +0100,NaN,None,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,69,None,None,None,None,None,HKQuantityTypeIdentifierBodyMass,Heloisa’s Iphone 🌸,15.2,kg,2022-01-10 16:17:02 +0100,2022-01-10 16:17:02 +0100,2022-01-10 16:17:02 +0100,NaN,None,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,68,None,None,None,None,None,HKQuantityTypeIdentifierBodyMass,Heloisa’s Iphone 🌸,15.2,kg,2022-01-27 22:35:16 +0100,2022-01-27 22:35:16 +0100,2022-01-27 22:35:16 +0100,NaN,None,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634994,43.8793,None,None,None,None,None,HKQuantityTypeIdentifierHeartRateVariabilitySDNN,Heloisa’s Apple Watch,9.6.2,ms,2023-09-21 09:46:52 +0100,2023-09-21 09:45:51 +0100,2023-09-21 09:46:48 +0100,NaN,"<<HKDevice: 0x2804a7c50>, name:Apple Watch, ma...",None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
634995,67.5935,None,None,None,None,None,HKQuantityTypeIdentifierHeartRateVariabilitySDNN,Heloisa’s Apple Watch,9.6.2,ms,2023-09-21 12:24:50 +0100,2023-09-21 12:23:48 +0100,2023-09-21 12:24:48 +0100,NaN,"<<HKDevice: 0x2804a7c50>, name:Apple Watch, ma...",None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
634996,51.2197,None,None,None,None,None,HKQuantityTypeIdentifierHeartRateVariabilitySDNN,Heloisa’s Apple Watch,9.6.2,ms,2023-09-21 12:30:22 +0100,2023-09-21 12:29:20 +0100,2023-09-21 12:30:20 +0100,NaN,"<<HKDevice: 0x2804a7c50>, name:Apple Watch, ma...",None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
634997,33.9476,None,None,None,None,None,HKQuantityTypeIdentifierHeartRateVariabilitySDNN,Heloisa’s Apple Watch,9.6.2,ms,2023-09-21 14:43:20 +0100,2023-09-21 14:42:18 +0100,2023-09-21 14:43:18 +0100,NaN,"<<HKDevice: 0x2804a7c50>, name:Apple Watch, ma...",None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
634998,47.9173,None,None,None,None,None,HKQuantityTypeIdentifierHeartRateVariabilitySDNN,Heloisa’s Apple Watch,9.6.2,ms,2023-09-21 16:45:33 +0100,2023-09-21 16:44:32 +0100,2023-09-21 16:45:31 +0100,NaN,"<<HKDevice: 0x2804a7c50>, name:Apple Watch, ma...",None,NaN,None,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
file.columns

In [ ]:
file.isna().sum()